# -*- coding: utf-8 -*-
"""Un7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UxwnxhQWq79quQoOzxVrARrGrE1RgmV
"""

#app.py
import sys
!{sys.executable} -m pip install streamlit


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Student Performance Analysis", layout="wide")

st.title("/content/student_data (1).csv")


df = pd.read_csv("/content/student_data (1).csv")

st.subheader("Dataset")
st.dataframe(df)

st.subheader("Dataset Information")
st.write("Rows:", df.shape[0])
st.write("Columns:", df.shape[1])

st.subheader("Summary Statistics")
st.write(df.describe())

st.subheader("Missing Values")
st.write(df.isnull().sum())


if "G3" in df.columns:
    st.subheader("Final Grade Distribution")

    fig, ax = plt.subplots()
    sns.histplot(df["G3"], bins=10, kde=True, ax=ax)
    st.pyplot(fig)


numeric_df = df.select_dtypes(include="number")

st.subheader("Correlation Heatmap")

fig, ax = plt.subplots(figsize=(10,8))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
st.pyplot(fig)

#EDA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("/content/student_data (1).csv")

print(df.head())

print(df.info())

print(df.describe())

print(df.isnull().sum())


if "G3" in df.columns:
    plt.figure(figsize=(6,4))
    sns.histplot(df["G3"], bins=10, kde=True)
    plt.title("Final Grade Distribution")
    plt.show()


numeric_df = df.select_dtypes(include="number")

plt.figure(figsize=(10,8))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("/content/student_data (1).csv")

sns.set_style("whitegrid")

plt.figure(figsize=(6,4))
sns.histplot(df["age"], bins=10, kde=True)
plt.title("Age Distribution")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="sex", data=df)
plt.title("Gender")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="studytime", data=df)
plt.title("Study Time")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="failures", data=df)
plt.title("Failures")
plt.show()


plt.figure(figsize=(6,4))
sns.histplot(df["absences"], bins=15)
plt.title("Absences")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="health", data=df)
plt.title("Health")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="traveltime", data=df)
plt.title("Travel Time")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="freetime", data=df)
plt.title("Free Time")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="goout", data=df)
plt.title("Go Out")
plt.show()


plt.figure(figsize=(6,4))
sns.histplot(df["G3"], bins=10, kde=True)
plt.title("Final Grade (G3)")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df["G1"], bins=10)
plt.title("G1 Marks")
plt.show()


plt.figure(figsize=(6,4))
sns.histplot(df["G2"], bins=10)
plt.title("G2 Marks")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="internet", data=df)
plt.title("Internet Access")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="activities", data=df)
plt.title("Activities")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="higher", data=df)
plt.title("Higher Education")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="romantic", data=df)
plt.title("Romantic Relationship")
plt.show()


plt.figure(figsize=(6,4))
sns.countplot(x="Dalc", data=df)
plt.title("Weekday Alcohol")
plt.show()
plt.figure(figsize=(6,4))
sns.countplot(x="Walc", data=df)
plt.title("Weekend Alcohol")
plt.show()


plt.figure(figsize=(6,4))
sns.boxplot(y=df["G3"])
plt.title("Boxplot of G3")
plt.show()


plt.figure(figsize=(12,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/student_data (1).csv")

plt.figure(figsize=(8,5))
sns.histplot(df["age"], bins=10, kde=True, color="blue")
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Students")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/student_data (1).csv")

plt.figure(figsize=(8,5))
sns.countplot(x="studytime", data=df)
plt.title("Study Time")
plt.xlabel("Study Time")
plt.ylabel("Students")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/student_data (1).csv")

plt.figure(figsize=(8,5))
sns.countplot(x="failures", data=df)
plt.title("Student Failures")
plt.xlabel("Failures")
plt.ylabel("Students")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/student_data (1).csv")

plt.figure(figsize=(8,5))
sns.histplot(df["absences"], bins=15, color="green")
plt.title("Student Absences")
plt.xlabel("Absences")
plt.ylabel("Students")
plt.show()

